version: 2.1

jobs:
  check-style:
    docker:
      - image: mcr.microsoft.com/dotnet/sdk:5.0
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            dotnet tool install -g dotnet-format
      - run:
          name: Check Code Formatting
          command: |
            export PATH="$PATH:/root/.dotnet/tools"
            dotnet-format Deadblock.csproj --fix-style warn --check -v diag
  test-build:
    docker:
      - image: mcr.microsoft.com/dotnet/core/sdk:3.1-focal
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update
            apt-get install -y libpng-dev
      - run:
          working_directory: ~
          name: Try Building
          command: |
            dotnet build Deadblock.csproj --configuration release
workflows:
  sample:
    jobs:
      - check-style
      - test-build
